복습

In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

data =  {
    "study_hours": [1,2,3,3,4,4,5,6,7,8],
    "attendance": [50,55,60,80,60,75,75,80,90,95],
    "pass_fail": [0,0,0,1,0,1,1,1,1,1]
}

df =pd.DataFrame(data)

# 입력값과 정답 분리
X = df[["study_hours", "attendance"]]
y = df["pass_fail"]

model = DecisionTreeClassifier(random_state=42)
model.fit(X,y)

print("데이터 준비 완료")
print(f"학생 수: {len(df)}명") ## 학생 수 : %% 명

데이터 준비 완료
학생 수: 10명

모델 정확도

- 학습에 사용한 데이터로 정확도 확인

In [4]:
accuracy = model.score(X, y )
print("모델 정확도:", accuracy) # 0~1 표시됨 -> 0~100%
print(f"모델 정확도 퍼센트:{accuracy * 100}%")

모델 정확도: 1.0
모델 정확도 퍼센트:100.0%

In [5]:
# 모델이 어떤 예측을 했는지 확인
predictions = model.predict(X)

# columns - 공부시간, 출석률, 실제, 예측, 결과
# zip() => zip([1,2,3], [4,5,6]) ==> (1,4), (2,5), (3,6)  ## 배열 대괄호 같아야 한다
# 실제값가 예측값을 한쌍으로 묶어서... 
# for a, p in zip(y, predictions):
# if (a == p):
#            print("0")
# else:
#            print("X")               --> 이런게 다 람다형식?


result = pd.DataFrame({
    "공부시간": X["study_hours"].values,
    "출석률": X["attendance"].values,
    "pass_fail": y.values,    ## X 는 끝난거고 y는 배열이 한개니깐 그냥 values 라고만 적기
    "예측": predictions,
    "결과": ["0" if a == p else "X" for a, p in zip(y, predictions)]            # y 실제값    예측값:predictions    [ ]   -- > 대괄호는 배열처리
 })

result

   공부시간  출석률  pass_fail  예측 결과
0     1   50          0   0  0
1     2   55          0   0  0
2     3   60          0   0  0
3     3   80          1   1  0
4     4   60          0   0  0
5     4   75          1   1  0
6     5   75          1   1  0
7     6   80          1   1  0
8     7   90          1   1  0
9     8   95          1   1  0

# 딕셔너리

key-Value 한쌍으로 이루어진 집합(자료형)

- List -> 번호표가 있는 사물함 (0번, 1번, 2번...)  #list = 배열
- Dictionary -> 이름표가 있는 사물함 (학번, 이름, 학년)

In [6]:
# 리스트
student_list = ["kim", 20, 50]
print(f"리스트에서 이름 출력: {student_list[0]}")

# 딕셔너리
student_dict = {"name": "kim", "age": 20, "score":50}
print(f"딕셔너리에서 이름 출력: {student_dict["name"]}")

리스트에서 이름 출력: kim
딕셔너리에서 이름 출력: kim

In [7]:
person = {
    "name": "주민우",
    "age": 23,
    "major": "AI응용프로그래밍"
}

# 전체 출력
print(person)

# 나이 출력
print (person["age"])

# 과목 출력
print(person["major"])

{'name': '주민우', 'age': 23, 'major': 'AI응용프로그래밍'}
23
AI응용프로그래밍

In [8]:
person["age"] = 21
print(person["age"], person)

# 성별 추가
person["gender"] = "male"
print(person)

# 성별 삭제
del person["gender"]   # del = delete 삭제하는거
print(person)

21 {'name': '주민우', 'age': 21, 'major': 'AI응용프로그래밍'}
{'name': '주민우', 'age': 21, 'major': 'AI응용프로그래밍', 'gender': 'male'}
{'name': '주민우', 'age': 21, 'major': 'AI응용프로그래밍'}

## 문제

- 사과,바나나,포도는 각 1000원, 2000원, 3000원 이다.
          - 딕셔너리 로그 출력
- 사과의 가격을 10% 할인하고 바나나는 13% 인상했을 때,
          -Python 코드로 작성
- 사과, 바나나, 포도의 가격표를 표시하세요. 
          - 로그 출력 (DataFrame 사용)

In [9]:
import pandas as pd

fruit_prices = {"사과": 1000, "바나나": 2000, "포도": 3000}
print("1. 초기 가격 딕셔너리:", fruit_prices)

updated_prices = {
    "사과": int(fruit_prices["사과"] * 0.9),
    "바나나": int(fruit_prices["바나나"] * 1.13),
    "포도": fruit_prices["포도"]
}

df = pd.DataFrame({
    "품목": list(updated_prices.keys()),
    "최종 가격": list(updated_prices.values())
})

print("\n2. 최종 가격표 (DataFrame):")
print(df.to_string(index=False))

1. 초기 가격 딕셔너리: {'사과': 1000, '바나나': 2000, '포도': 3000}

2. 최종 가격표 (DataFrame):
 품목  최종 가격
 사과    900
바나나   2260
 포도   3000

## 딕셔너리와 반복문 함께 사용

In [10]:
scores = {
    "국어": 88,
    "수학": 76,
    "영어": 92
}

# 로그 출력 ------------
# 국어 : 88점
# 수학:  76점
# 영어:  92점

for subject, score in scores.items():
    print(f"{subject}: {score}점")

국어: 88점
수학: 76점
영어: 92점

In [11]:
# 80점 이상인 과목만 출력

for subject, score in scores.items():
    if score >= 80:
        print(f"80점 이상인 과목: {subject}")

80점 이상인 과목: 국어
80점 이상인 과목: 영어

# Pandas DataFrame 다루기

In [12]:
import pandas as pd

data =  {
    "study_hours": [1,2,3,3,4,4,5,6,7,8],
    "attendance": [50,55,60,80,60,75,75,80,90,95],
    "pass_fail": [0,0,0,1,0,1,1,1,1,1]
}

df = pd.DataFrame(data)
df

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0
3            3          80          1
4            4          60          0
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

In [13]:
# 상위 3줄만 보기

print(df.head(3))  # print df로도 바꿀 수 있음 표가 달라짐   df.head(3)

   study_hours  attendance  pass_fail
0            1          50          0
1            2          55          0
2            3          60          0

In [14]:
# 기본 통계 보기
# count - 데이터 개수
# mean - 평균값 (전체 나누기 개수)
# std - 표준편차 (평균에서 얼마나 퍼져 있는지, 클수록 편차가 큼)
# min - 최솟값
# 25% - 하위 25% (0부터 시작하니깐)
# 50% - 중앙값
# 75% - 상위 25%
# max - 최댓값
df.describe()

       study_hours  attendance  pass_fail
count    10.000000   10.000000  10.000000
mean      4.300000   72.000000   0.600000
std       2.213594   15.129074   0.516398
min       1.000000   50.000000   0.000000
25%       3.000000   60.000000   0.000000
50%       4.000000   75.000000   1.000000
75%       5.750000   80.000000   1.000000
max       8.000000   95.000000   1.000000

In [15]:
# 조건으로 데이터 골라내기
high_attendance = df[df["attendance"] >= 70]
#high_attendance

# 합격한 학생만 출력
pass_student = df[df["pass_fail"] == 1] 
pass_student

   study_hours  attendance  pass_fail
3            3          80          1
5            4          75          1
6            5          75          1
7            6          80          1
8            7          90          1
9            8          95          1

날씨 예측

In [16]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [17]:
# 데이터 준비

weather_data = {
    "clouds": [10,20,30,50,60,70,80,90,95,40],
    "humidity": [30,35,40,55,65,70,80,85,90,45],
    "umbrella": [0, 0, 0, 0 ,1 ,1 ,1 ,1 ,1 ,0]
}

weather_df = pd.DataFrame(weather_data)
weather_df

   clouds  humidity  umbrella
0      10        30         0
1      20        35         0
2      30        40         0
3      50        55         0
4      60        65         1
5      70        70         1
6      80        80         1
7      90        85         1
8      95        90         1
9      40        45         0

In [18]:
# 입력값과 정답 분리

X_weather = weather_df[["clouds", "humidity"]]
y_weather = weather_df["umbrella"]

print("입력값과 정답 분리 완료")

입력값과 정답 분리 완료

In [19]:
# 모델 만들기 + 학습
weather_model = DecisionTreeClassifier(random_state=42)
weather_model.fit(X_weather, y_weather)  # fit  학습하라는뜻
print("모델 학습 완료")

모델 학습 완료

In [20]:
# 예측하기
test_weather = pd.DataFrame([
        [20,35], # 구름 적고 습도 낮음
        [55,60], # 구름 보통, 습도 보통
        [85,88], # 구름 많음, 습도 높음          
    ], columns=["clouds", "humidity"])

predictions = weather_model.predict(test_weather)
predictions

array([0, 0, 1])

## 문제

아래 로그 개별 출력
- 구름 ?%, 습도 ?% -> 우산 필요|불필요
  - 예시> 구름 20%, 습도 35% -> 우산 불필요

In [21]:
for i in range(len(test_weather)):
    clouds = test_weather.iloc[i]["clouds"]
    humidity = test_weather.iloc[i]["humidity"]
    
    if predictions[i] == 1:
        print(f"구름 {clouds}%, 습도 {humidity}% -> 우산 필요")
    else:
        print(f"구름 {clouds}%, 습도 {humidity}% -> 우산 불필요")

구름 20%, 습도 35% -> 우산 불필요
구름 55%, 습도 60% -> 우산 불필요
구름 85%, 습도 88% -> 우산 필요

In [22]:
# 모델 정확도 구하기


acc = weather_model.score(X_weather, y_weather)
print(f"모델 정확도: {acc * 100}%")

모델 정확도: 100.0%

In [23]:
# 모델 정확도 낮추기
# 애매한 데이터를 포함한 날씨 데이터

messy_data = {
    "cloudy":  [10, 20, 55, 55, 60 ,70, 80, 90],
    "humidity": [30,35,60,60,65,70,80,85], 
    "umbrella": [0,0,0,1,1,1,1,1],
}

messy_df = pd.DataFrame(messy_data)


X_messy = messy_df[["cloudy", "humidity"]]
y_messy = messy_df["umbrella"]


messy_model = DecisionTreeClassifier(random_state=42)
messy_model.fit(X_messy, y_messy)

messy_acc = messy_model.score(X_messy, y_messy)
print(f"애매한 데이터 모델 정확도: {messy_acc * 100}%")

print()

messy_pred = messy_model.predict(X_messy)
result = pd.DataFrame({
    "구름량": X_messy["cloudy"].values,
    "습도": X_messy["humidity"].values,
    "umbrella": y_messy.values,    ## X 는 끝난거고 y는 배열이 한개니깐 그냥 values 라고만 적기
    "예측": messy_pred,
    "결과": ["0" if a == p else "X" for a, p in zip(y_messy, messy_pred)]            # y 실제값    예측값:predictions    [ ]   -- > 대괄호는 배열처리
 })

result

애매한 데이터 모델 정확도: 87.5%

   구름량  습도  umbrella  예측 결과
0   10  30         0   0  0
1   20  35         0   0  0
2   55  60         0   0  0
3   55  60         1   0  X
4   60  65         1   1  0
5   70  70         1   1  0
6   80  80         1   1  0
7   90  85         1   1  0