# 문자열 심화

## 대소문자 변환

In [1]:
text = "Hello, Python!"

print(text)
print(text.upper())
print(text.lower())

Hello, Python!
HELLO, PYTHON!
hello, python!

## 공백 제거

In [2]:
name = "          Python        "

print(f"원본:  '{name}'")    # name.trim()  java 에서는 
print(f"정리 후: '{name.strip()}'")

# 변수와 String 비교
print("공백이 있을 때 비교:", name == "Python")
print("공백 제거 후 비교:", name.strip() == "Python")

원본:  '          Python        '
정리 후: 'Python'
공백이 있을 때 비교: False
공백 제거 후 비교: True

## 문자열 바꾸기

In [3]:
sentence = "파이썬을 배우고 있습니다. 파이썬은 재미있습니다."

new_sentence = sentence.replace("파이썬", "Python")

print("원본:", sentence)
print("수정:", new_sentence)

원본: 파이썬을 배우고 있습니다. 파이썬은 재미있습니다.
수정: Python을 배우고 있습니다. Python은 재미있습니다.

In [4]:
price = "1,500,000원"
clean_price = price.replace(",", "").replace("원", "")
print(int(clean_price))

1500000

## 문자열 나누기

In [5]:
words = "사과,바나나,포도,딸기"
word_list=words.split(",")
print(word_list, len(word_list))

['사과', '바나나', '포도', '딸기'] 4

## 문자열 자르기

In [6]:
phone = "010-1234-5678"

# 앞에서 3글자
print(phone[0:3])
# 가운데 4글자
print(phone[4:8])
# 마지막 4글자
print(phone[-4:])   # -1이 맨 끝   4:7이 아닌 이유는 하이픈 - 때문에

010
1234
5678

## 문제
이메일 주소에서 아이디와 도메인을 분리하세요.

In [7]:
email = "12345@email.daelim.ac.kr"

parts = email.split("@")
user_id = parts[0]
domain = parts[1]

print("이메일:", email)
print("아이디:", user_id)
print("도메인:", domain)

이메일: 12345@email.daelim.ac.kr
아이디: 12345
도메인: email.daelim.ac.kr

## 문자열 검색

In [9]:
review = "이 제품은 정말 좋아요! 배송도 빠르고 품질도 훌륭합니다."


print("좋아요 포함:", "좋아요" in review)
print("나빠요 포함:", "나빠요" in review)

if "좋아요" in review or "훌륭" in review:
    print("긍정적 리뷰")
else:
    print("부정적 리뷰")

좋아요 포함: True
나빠요 포함: False
긍정적 리뷰

## 함수 심화

## 함수 기본값

In [10]:
def greet(name, greeting="환영합니다"):
    print(f"{name}님, {greeting}")

greet("대림대")
greet("대림대", "안녕하세요")

대림대님, 환영합니다
대림대님, 안녕하세요

In [11]:
# 할인율 계산
# discount: 0.0~1.0 (0%~100%)
def calculate_price(price, discount=0):
    discounted = price * (1 - discount)
    return discounted


print(f"기본 가격: {calculate_price(10000)}원")
print(f"할인 가격: {calculate_price(10000, 0.1)}원")

기본 가격: 10000원
할인 가격: 9000.0원

## 함수에서 여러값 반환하기

In [12]:
# 최솟값과 최댓값을 동시 반환하는 함수
def min_max(numbers):
    minimum = min(numbers)
    maximum = max(numbers)
    return minimum, maximum


scores = [10,20,30,40,50,60,70,80]
low, high = min_max(scores)
print("최솟값:", low)  
print("최댓값:", high)

최솟값: 10
최댓값: 80

## 문제

class_scores = [45,62,78,55,90,83,71,66,48,95]


성적 분석 함수 생성
아래와 같은 로그 출력
    - 평균: x.x 점(소수점 1번째까지만 출력)
    - 최고점: xx점
    - 최저점: xx점
    - 합격(60점 이상): x명

In [13]:
class_scores = [45, 62, 78, 55, 90, 83, 71, 66, 48, 95]

def analyze_scores(scores):
    avg = sum(scores) / len(scores)
    high = max(scores)
    low = min(scores)

    count = 0
    for s in scores:
        if s >= 60:
            count += 1

    print(f"평균: {avg:.1f} 점")
    print("최고점:", high, "점")
    print("최저점:", low, "점")
    print("합격(60점 이상):", count, "명")


analyze_scores(class_scores)

평균: 69.3 점
최고점: 95 점
최저점: 45 점
합격(60점 이상): 7 명

Pandas 심화

In [14]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [15]:
# 학생 데이터
grade_data = {
    "name": ["kim", "lee", "park", "cho", "choi", "jung"],
    "korean": [88      ,    72,          95      ,        65     ,    80      , 91],
    "math": [  75      ,    90,          65      ,        85     ,    77      , 81],
    "english": [  82      ,    40,          55      ,        25     ,    67      , 71],

}

grade_df= pd.DataFrame(grade_data)
grade_df

   name  korean  math  english
0   kim      88    75       82
1   lee      72    90       40
2  park      95    65       55
3   cho      65    85       25
4  choi      80    77       67
5  jung      91    81       71

## 정렬하기

In [19]:
print("----  국어 점수 낮은 순 -----")
print(grade_df.sort_values("korean"))
print()
print("----- 수학 점수 높은 순 -----")
print(grade_df.sort_values("math", ascending=False))

----  국어 점수 낮은 순 -----
   name  korean  math  english
3   cho      65    85       25
1   lee      72    90       40
4  choi      80    77       67
0   kim      88    75       82
5  jung      91    81       71
2  park      95    65       55

----- 수학 점수 높은 순 -----
   name  korean  math  english
1   lee      72    90       40
3   cho      65    85       25
5  jung      91    81       71
4  choi      80    77       67
0   kim      88    75       82
2  park      95    65       55

## 새로운 열 추가하기

In [22]:
grade_df["average"] = \
    (grade_df["korean"] + \
        grade_df["math"] + \
            grade_df["english"]) / 3         # \ 다음 줄
grade_df["average"] = grade_df["average"].round(1)
grade_df

   name  korean  math  english  average
0   kim      88    75       82     81.7
1   lee      72    90       40     67.3
2  park      95    65       55     71.7
3   cho      65    85       25     58.3
4  choi      80    77       67     74.7
5  jung      91    81       71     81.0

In [23]:
grade_df["grade"] = grade_df["average"].apply(
    lambda x: "A" if x >= 80 else "B"
)

grade_df

   name  korean  math  english  average grade
0   kim      88    75       82     81.7     A
1   lee      72    90       40     67.3     B
2  park      95    65       55     71.7     B
3   cho      65    85       25     58.3     B
4  choi      80    77       67     74.7     B
5  jung      91    81       71     81.0     A

## 그룹별 통계

In [24]:
group_avg = grade_df.groupby("grade")["average"].mean()    # 위에 열을 가져와야 해서 average 대괄호
print("등급별 평균:")
print(group_avg)

등급별 평균:
grade
A    81.35
B    68.00
Name: average, dtype: float64

In [26]:
# 응용 - 회사 부서별 급여 파악

employee_data = {
    "name": ["kim", "lee", "park", "cho", "choi", "jung"],
    "department": ["개발", "마케팅", "개발", "인사", "마케팅", "인사"],
    "salary": [4200, 3500, 5000, 6000, 7000, 6500]

}
    
emp_df = pd.DataFrame(employee_data)
emp_df

# 부서별 평균 급여

print("---- 부서별 평균 급여 ----")
dept_avg = emp_df.groupby("department")["salary"].mean()
print(dept_avg.round(0))
print()
print("---- 부서별 인원 수 ----")
dept_count = emp_df.groupby("department")["name"].count()
print(dept_count)

---- 부서별 평균 급여 ----
department
개발     4600.0
마케팅    5250.0
인사     6250.0
Name: salary, dtype: float64

---- 부서별 인원 수 ----
department
개발     2
마케팅    2
인사     2
Name: name, dtype: int64